### ISSUE TITLE
Can this MR_SLAM integrate global location information

### ISSUE THREAD

**Issue by Joosoo1** [MaverickPeter/MR_SLAM#13]
Can the inclusion of global location data, such as GPS, enhance the quality of something? accuracy and success of MR_SLAM? If it can, then what aspects of GPS information should be incorporated, How should I incorporate GPS information into MR_SLAM. please give us some suggestions.

**Comment by MaverickPeter** [comment]
GPS information can be used to enhance the mapping quality, but the current version cannot handle the inclusion of GPS information. There are two aspects that can be incorporated. First, in the initialization step, the current version only supports zero initialization and manual configuration With the incorporation of GPS, the initialization can be handled, and the calculation of the back-end optimization can be reduced. Second, during the task, the GPS information can be considered as a factor in the pose graph; you can refer to the [LIO-SAM](https://github.com/TixiaoShan/LIO-SAM/blob/0be1fbe6275fb8366d5b800af4fc8c76a885c869/src/mapOptmization.cpp#L1397) for the detailed implementation.   I'll also add this function in future updates.

**Comment by Joosoo1** [comment]
OK, thanks for your reply. i will try.
