### ISSUE TITLE
 /usr/local/lib/cmake/fftw3/FFTW3Config.cmake:13 (include):

### ISSUE THREAD

**Issue by 1466758326** [MaverickPeter/MR_SLAM#17]
Hello, I am Liang Yapeng from Wuhan University. I am very interested in your work on GitHub, but I encounter issues connecting when trying to clone. I would like to seek some advice on this.

----------------------------------
- Found PCL: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_features;pcl_sample_consensus;pcl_filters;pcl_io;pcl_registration;pcl_visualization;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/libOpenNI.so;/usr/lib/libOpenNI2.so;vtkChartsCore;vtkCommonColor;vtkCommonCore;vtksys;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkCommonExecutionModel;vtkFiltersGeneral;vtkCommonComputationalGeometry;vtkFiltersCore;vtkInfovisCore;vtkFiltersExtraction;vtkFiltersStatistics;vtkImagingFourier;vtkImagingCore;vtkalglib;vtkRenderingContext2D;vtkRenderingCore;vtkFiltersGeometry;vtkFiltersSources;vtkRenderingFreeType;/usr/lib/x86_64-linux-gnu/libfreetype.so;/usr/lib/x86_64-linux-gnu/libz.so;vtkFiltersModeling;vtkImagingSources;vtkInteractionStyle;vtkInteractionWidgets;vtkFiltersHybrid;vtkImagingColor;vtkImagingGeneral;vtkImagingHybrid;vtkIOImage;vtkDICOMParser;vtkmetaio;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libtiff.so;vtkRenderingAnnotation;vtkRenderingVolume;vtkIOXML;vtkIOCore;vtkIOXMLParser;/usr/lib/x86_64-linux-gnu/libexpat.so;vtkIOGeometry;vtkIOLegacy;vtkIOPLY;vtkRenderingLOD;vtkViewsContext2D;vtkViewsCore;vtkRenderingContextOpenGL2;vtkRenderingOpenGL2;FLANN::FLANN  
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include;/usr/include;/usr/local/include/gtsam/3rdparty/Eigen/
CMake Error at /usr/local/lib/cmake/fftw3/FFTW3Config.cmake:13 (include):
  include could not find load file:

    /usr/local/lib/cmake/fftw3/FFTW3LibraryDepends.cmake
Call Stack (most recent call first):
  global_manager/CMakeLists.txt:48 (find_package)

-- Found CUDA: /usr/local/cuda-11.3 (found suitable version "11.3", minimum required is "10") 
-- Found Boost: /usr/include (found version "1.71.0") found components: serialization filesystem timer system program_options thread chrono date_time atomic

**Comment by MaverickPeter** [comment]
@1466758326  It's a dependency problem; you need to install fftw3 library (https://www.fftw.org/)

**Comment by 1466758326** [comment]
It has been installed through 3.3.10 and the following method is used. Is it correct? However, this problem still occurs afterwards.
./configure
make
sudo make istall

**Comment by 1466758326** [comment]
It is indeed an installation problem. You need to build the build to install it. The problem has been solved.

**Comment by 1466758326** [comment]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import gputransform
ModuleNotFoundError: No module named 'gputransform'

**Comment by MaverickPeter** [comment]
@1466758326 You need to follow the README in [disco/tools](https://github.com/MaverickPeter/MR_SLAM/tree/main/LoopDetection/src/disco_ros/tools/multi-layer-polar-gpu/cython) and build gputransform
