### ISSUE TITLE
some question about “merged_elevation_map”

### ISSUE THREAD

**Issue by Joosoo1** [MaverickPeter/MR_SLAM#19]
Hi, is it necessary to enable the `elevation_mapping` module for the construction of `erged_elevation_map` in `global_manager`, I noticed that `elevation_mapping` transmits a `submap` to `global_manager` as well, is it possible to just Is it possible to transmit only the front-end `LIO` submap to build `erged_elevation_map` to generate the global `costmap`?

**Comment by MaverickPeter** [comment]
@Joosoo1  It's not necessary to enable the elevation_mapping module to build a costmap. With some simplification, you can also generate a global costmap using the 3D point cloud merged from submaps provided by LIO. Specifically, you need to write a plugin in costmap dir for this. Note that the elevation mapping package provides a more accurate analysis of the terrain.
