### ISSUE TITLE
Full usage demo

### ISSUE THREAD

**Issue by guo253** [MaverickPeter/MR_SLAM#2]
Hi!
Thank you for the great job!
1.Can you provide a bag file for full usage?
2.if I want to use single robot for big map, how can I follow the full usage steps? 
3.if I want to use another loop closure method instead of the disco, how can I modify the code?

Thank you again!!!

**Comment by WilliamWoo45** [comment]
Hi @MaverickPeter,

Bravo for the great work! I have similar questions with the questions No.1 and No.3 raised by @guo253.

Can you provide a bag file for full usage demo? 
And do you have any idea for implementing other loop closing modules apart from the `DiSCO` and `RING`? 

Thanks. 

Best Regards,
William
