### ISSUE TITLE
The minimum computer hardware configuration

### ISSUE THREAD

**Issue by cxmzdd** [MaverickPeter/MR_SLAM#20]
First , thank you very much for opening up this project . I want to follow your project on low computing platforms . what's the suitable cpu and gpu.

**Comment by MaverickPeter** [comment]
@cxmzdd 
Thanks for your following. There are two parts in this project. The first one is the onboard computation of mapping, trajectory following, and odometry which I suggest using a Jetson Xavier NX or a better computer to meet the real-time requirements. The other one is the center station which is in charge of global mapping, data association, and global planning, I suggest using a relatively powerful PC. We don't evaluate the minimum requirements, I can only provide a reference that in 3-dog experiments, the PC is equipped with i7-10700 CPU with 32GB memory and RTX 2060 Super GPU. During the experiments, the CPU and GPU load is lower than 75%. Hope this information can help you.

**Comment by cxmzdd** [comment]
Thanks for your answer. This work has any public paper? I try to find this work's paper for some details. But it fails.

**Comment by MaverickPeter** [comment]
@cxmzdd 
This project is a system implementation of our global localization paper: "RING++: Roto-Translation-Invariant Gram for Global Localization on a Sparse Scan Map".
