### ISSUE TITLE
multi LIO map merge

### ISSUE THREAD

**Issue by wolf943134497** [MaverickPeter/MR_SLAM#22]
Hi @MaverickPeter  Thanks for your great works!

MR_SLAM is a great project for multi robot/session slam, and it include multi modules. Full usage of MR_SLAM is very complicated.  

I just want use MR_SLAM for multi lidar mapping, and I have multi session data at different site and time(i.e.,  point cloud scans,  point cloud scans pose,  point cloud scans loop closure descriptors  and global map of the session for each session) , I want to merge multi session lio global map to one global map by using MR_SLAM. can I  only use the global_manager module to achieve the goal?  elevation_mapping, preprocess tools and costmap module does not need to be run ? can you give me some advice? Thanks a lot!

**Comment by MaverickPeter** [comment]
Hi @wolf943134497 Thanks for your following.
I suggest you generate a rosbag file with all your scans , poses, such as the bag we provided: https://drive.google.com/file/d/1KNrzvpfeuiQ8i-zUvlKbsn-iTIPJOQh8/view?pli=1. If you want to use your own loop descriptors, you also need to write your own loop detection module, which can be found at https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/RING_ros/main_RING.py. 
Currently, the repo cannot support offline merging, but we will consider add this feature later.

**Comment by wolf943134497** [comment]
> Hi @wolf943134497 Thanks for your following.
> 
> I suggest you generate a rosbag file with all your scans , poses, such as the bag we provided: https://drive.google.com/file/d/1KNrzvpfeuiQ8i-zUvlKbsn-iTIPJOQh8/view?pli=1. If you want to use your own loop descriptors, you also need to write your own loop detection module, which can be found at https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/RING_ros/main_RING.py.
> 
> Currently, the repo cannot support offline merging, but we will consider adding this feature later.

@MaverickPeter   Thanks for your rapid reply！ I will try it.  I think offline mode facilitates debugging.  Thanks for your great work!
