### ISSUE TITLE
For single robot application.

### ISSUE THREAD

**Issue by cxmzdd** [MaverickPeter/MR_SLAM#23]
Hello author, thank you very much for open sourcing this project.
FAST-LIO will experience drift during loopback.So i Attempt to change the loop back detection module,like this
![2024-04-10 15-06-01 的屏幕截图](https://github.com/MaverickPeter/MR_SLAM/assets/94447177/23d846db-4990-45e4-9825-bc4752a345d9)
But there was an error in the global_manager module
![2024-04-10 15-06-58 的屏幕截图](https://github.com/MaverickPeter/MR_SLAM/assets/94447177/5aa0906e-59ac-4967-966c-04a924261a64)
and i noticed that MR SLAM supports single robot applications, Can you give me some help for this. Thanks

**Comment by MaverickPeter** [comment]
@cxmzdd Thanks for following our work. 
I cannot understand the first question. The drift is common in FAST-LIO, and the loopback problem is caused by the loop play of the rosbag, which is not the problem of the loop detection module. 
As for single robot application, the error indicates that the robotid is mismatched. You may modify the start_robot_id in launch file.

**Comment by cxmzdd** [comment]
Thanks for your reply.
I'm sorry I didn't express myself clearly. I mean FAST-LIO will experience drift during loopback. Is there a way to eliminate this drift.
I noticed there is a "odometry_loop_enable" parameter,Perhaps I can change it to true to achieve my goal？

**Comment by MaverickPeter** [comment]
@cxmzdd odometry_loop_enable is only enabled using built-in loop detection which is not recommended. The way to achieve single robot SLAM, you need to activate the corresponding lines to detect inter-robot loops. https://github.com/MaverickPeter/MR_SLAM/blob/a46cbadac6400f4a815dcabe806e02ed67d17a0f/LoopDetection/src/RING_ros/main_RING.py#L276C4-L277C116. Also you need to comment out the inter-robot check in this line: https://github.com/MaverickPeter/MR_SLAM/blob/a46cbadac6400f4a815dcabe806e02ed67d17a0f/LoopDetection/src/RING_ros/main_RING.py#L213

**Comment by cxmzdd** [comment]
@MaverickPeter Thank you for your advise.i've tried it.But the mapping wil crash when receiving loop.
```
[ INFO] [1713874305.252086589, 1705910721.077912261]:  received loop update 
[global_manager-1] process has died [pid 636399, exit code -11, cmd /home/Mapping/devel/lib/global_manager/global_manager_node __name:=global_manager __log:=/root/.ros/log/54aaab66-015c-11ef-9537-0242ac110002/global_manager-1.log].
log file: /root/.ros/log/54aaab66-015c-11ef-9537-0242ac110002/global_manager-1*.log
```

**Comment by MaverickPeter** [comment]
@cxmzdd  Could you please share your launch file and loop detection python file? I'll check it out.

**Comment by cxmzdd** [comment]
Sure,here is the launch file:[https://gist.github.com/cxmzdd/8259728c2946ada907860388cc12d2cd](url) i only change the "start_robot_id" to 2.
And this is the loop detection python file:[https://gist.github.com/cxmzdd/5472b1247da6cefc3798691b42b60fa0](url). i use `detect_loop_single_icp` to add a time limit for single robot loop back detection,and change some parameters for icp to run faster

**Comment by MaverickPeter** [comment]
@cxmzdd  Sorry for the late reply. I'll try to reproduce your issue this weekend and try to fix it.

**Comment by MaverickPeter** [comment]
@cxmzdd You may need to use the callback1 to subscribe /robot_2/xxx in  main_RING.py to achieve single_robot application.

**Comment by cxmzdd** [comment]
I got it.
Thanks
