### ISSUE TITLE
few test questions 

### ISSUE THREAD

**Issue by wolf943134497** [MaverickPeter/MR_SLAM#24]
Hi @MaverickPeter  Thanks for your released codes.
I want to ask some questions:
 1. Did you compare Disco-SLAM with MR-SLAM，how much better is MR-SLAM
 2. I found that the test data 3_dog.bag was collected at the same moment, if I record data at different time, and the data have overlapping area, can MR-SLAM merge the data which collected at different time
 3. Do you have any relevant documents to introduce global_manager module
 
Thanks!

**Comment by MaverickPeter** [comment]
Hi @wolf943134497  
Thanks for following our work.
1. DiSCO-SLAM is a distributed SLAM system, and ours is a centralized SLAM, so we haven't compared these two systems.
2. If the recorded data is collected at different times, you can play the different bags simultaneously and only publish one clock topic to simulate the multi-robot collaboration.
3. We only have a brief introduction in Chinese. https://zhuanlan.zhihu.com/p/581173773

**Comment by wolf943134497** [comment]
Thanks for your quick reply and great work!
