### ISSUE TITLE
怎么用evo包评估结果

### ISSUE THREAD

**Issue by DioBakery** [MaverickPeter/MR_SLAM#25]
请问有没有图优化后的多机器人轨迹数据或文件？有的话是在哪里？并且怎么用evo包评估？

**Comment by MaverickPeter** [comment]
在建完图后，可以在终端rostopic pub /map_saving tab一下出来bool：false，改成True。在launch里面可以修改保存路径。导出后可以用evo评估，后面我会在Tool中上传一个格式转换的文件，将导出的数据改成evo 可以评估的格式。
