### ISSUE TITLE
关于SubMap消息

### ISSUE THREAD

**Issue by DioBakery** [MaverickPeter/MR_SLAM#29]
您好，在使用fulluse但未开启elevationmapping的时候，我发现/robot_x/submap/keyframe是有实际内容的，而/robot_x/submap/submap并没有实际内容，但disco和global_manager能够正常运行，请问这块内容的作用是什么呢？

**Comment by MaverickPeter** [comment]
@DioBakery submap是elevation map累积的地图，用于拼接全局elevation map，不会影响其他的部分，keyframe是用于回环和构建3D点云地图的，是从前端发起的，因此disco和global_manager依旧可以正常运行
