### ISSUE TITLE
Loop Detector Errors: DiSCO - No module named 'gputransform' & RING - Segmentation fault

### ISSUE THREAD

**Issue by WilliamWoo45** [MaverickPeter/MR_SLAM#6]
Hi @MaverickPeter,

Thanks for your pioneering work on multi-robot SLAM. 
I've successfully installed `MR_SLAM` on my laptop (`Ubuntu 20.04, ROS Noetic`), however there are some problems for both of the two loop detector modules as follows:

1. For the **`DiSCO`** **Loop Detector**: have the module "`gputransform`" not found error. I checked and confirmed that the [gputransform.cpython-38-x86_64-linux-gnu.so](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/disco_ros/gputransform.cpython-38-x86_64-linux-gnu.so) file is in the `disco_ros` directory. I also tried the `python3 setup.py install` command from [DiSCO-pytorch](https://github.com/MaverickPeter/DiSCO-pytorch). However, this error persists as shown in the figure below: 

![DiSCO_error](https://user-images.githubusercontent.com/43923666/230631454-35f6e240-ddc9-4227-af6e-39aa81c08761.png)

2. For the **`RING`** **Loop Detector**: the `Segmentation fault (core dumped)` issue persists, even if I have changed the system stack size by `ulimit -s 81920`. The error message is shown below:

- If executing the **RING-based** method [main.py](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/RING_ros/main.py), core will dump after detecting the first loop: 

![2023-04-07-MR_SLAM_RING-lc-failed](https://user-images.githubusercontent.com/43923666/230633067-0be0627d-707f-48ee-8186-7032532cb505.png)

And the map in `Rviz` will not be loop closed or corrected, as can be seen in this video: 

https://user-images.githubusercontent.com/43923666/230633552-a03a3617-3012-4106-9c0a-7c0194aec0d2.mp4

- If executing the **Scan Context-based** method [main_SC.py](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/RING_ros/main_SC.py), core will dump in the very beginning: 

![2023-04-07-main_SC-failed](https://user-images.githubusercontent.com/43923666/230633082-a41a20cd-7744-45ea-bb76-03624271e818.png)

So do you have any idea or suggestion for solving these issues? 
Thanks a lot and appreciate your early response.

Best Regards,
William

**Comment by MaverickPeter** [comment]
Hi @WilliamWoo45, thanks for following our work. We only test our code on Ubuntu 18.04 with ROS melodic so something might be different. We will try to reproduce your problem by setting up the same environment; before that, you may try some solutions yourself.
1. For the first question about DiSCO, you have to make sure that the Python version used in this workspace is the Python that you install the gputransformer.
2. For the problem related to RING and SC, it might be something wrong with the fast_gicp, you may need to check the installation of fast_gicp using the test code in fast_gicp repo.

**Comment by MaverickPeter** [comment]
Hi @WilliamWoo45, it's weird. I just comment out the 'import open3d as o3d' in the util.py and everything goes well.

**Comment by WilliamWoo45** [comment]
> Hi @WilliamWoo45, it's weird. For RING, I just comment out the 'import open3d as o3d' in the util.py and everything goes well.

Hi @MaverickPeter, 

Thanks for your prompt responses and actions :+1: !  It is indeed quite weird. 
I tried these solutions and confirmed that it works. So in order to make **RING** or **Scan Context-based method** work, the following 3 steps should be conducted: 
1.  After `git clone https://github.com/MaverickPeter/MR_SLAM.git`, make sure `cd` to /xxxx/LoopDetection/src/fast_gicp, then `git clone https://github.com/SMRT-AIST/fast_gicp --recursive` and install `fast_gicp` by executing `python3 setup.py install --user`
2. Comment out the line `import open3d as o3d` in the [util.py](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/RING_ros/util.py#L18) file. 
3. Use the command `python3.8 main.py` to launch the main file, since in my laptop both the python 3.10 and python 3.8 were installed and they seem to have some conflictions.  

================================================================================================

For the **DiSCO**, I'm still fighting with the "`gputransform`" not found error. It seems that I should run the command `python setup.py build_ext --inplace` in the directory [LoopDetection/src/disco_ros/tools/multi-layer-polar-cython/cython](https://github.com/MaverickPeter/MR_SLAM/tree/main/LoopDetection/src/disco_ros/tools/multi-layer-polar-cython/cython) and generate a new `gputransform.cpythonxxx.so` file, and copy it to the **main dir** of `disco_ros`. However, there pops out another error saying that `nvcc fatal: Value 'sm_30' is not defined for option 'gpu-architecture'` (see below). 
![nvcc_error](https://user-images.githubusercontent.com/43923666/231774017-de266e6e-8707-4748-996b-25c7c1b1e4d3.png)

I briefly searched for this error and found that it maybe related to the CUDA version. It seems that CUDA has dropping out support for sm_30 since CUDA version 11. I will update you if I have further progresses.

================================================================================================

BTW, is it possible for you to share some simple bags file for full usage demo? I'm very looking forward to see how MR_SLAM really works.

Cheers :)

Best Regards,
William

**Comment by MaverickPeter** [comment]
@WilliamWoo45 Thanks for your sharing. I'm preparing to update the instructions part of this repository.

For this error `nvcc fatal: Value 'sm_30' is not defined for option 'gpu-architecture`, you can simply comment out this line to solve it." https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/disco_ros/tools/multi-layer-polar-cython/cython/setup.py#LL125C18-L125C29

As for the full usage demo, I'll upload and share it in an upcoming update.

**Comment by WilliamWoo45** [comment]
Hi @MaverickPeter,

Thanks for your information. By commenting out the 'sm_30' related part, it indeed solves the error. 

So for the **DiSCO**, the running steps are as follows: 
1. I run the command `python setup.py build_ext --inplace` in the directory [LoopDetection/src/disco_ros/tools/multi-layer-polar-cython/cython](https://github.com/MaverickPeter/MR_SLAM/tree/main/LoopDetection/src/disco_ros/tools/multi-layer-polar-cython/cython) and generate a new `gputransform.cpythonxxx.so` file, and copy it to the **main dir** of `disco_ros`. 
2. As mentioned in issue #5, remember to change one line in the file [main.py](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/disco_ros/main.py) from [fitness = gicp.get_fitness_score(max_range=1.0)](https://github.com/MaverickPeter/MR_SLAM/blob/main/LoopDetection/src/disco_ros/main.py#L193) to `fitness = gicp.get_fitness_score(1.0)`. 
3. In the **main dir** of `disco_ros`, run the command `python3.8 main.py`. 


Looking forward to your early update for the full usage demo :+1: !

Best Regards,
William

**Comment by WilliamWoo45** [comment]
Hi @MaverickPeter,

It's been a while since we discussed last time. 
May I kindly check with you, is there any update on the repository instructions and full usage demo?

Cheers. 

Best Regards,
William

**Comment by MaverickPeter** [comment]
The full usage demo has been released.
