### ISSUE TITLE
Failed loop closure for full usage demo in Docker - wrong parameters settings?

### ISSUE THREAD

**Issue by WilliamWoo45** [MaverickPeter/MR_SLAM#7]
Hi @MaverickPeter,

Thanks for your update and release of the full usage demo!

I've tried to run the full usage bags in Docker. However, I found that if the parameter `icp_fitness_score` is set at **0.1 by default**, most of the loop candidates would be rejected and the point cloud maps are only partially shown (please see figures below).

![Reject the loop](https://github.com/MaverickPeter/MR_SLAM/assets/43923666/14ff01fd-23de-4f67-87fe-56a023ed1525)

![point clouds](https://github.com/MaverickPeter/MR_SLAM/assets/43923666/5186804a-e544-4982-b69f-ad23091b0efd)

![point cloud with routes](https://github.com/MaverickPeter/MR_SLAM/assets/43923666/ae3839cf-2713-45d3-bd44-838f5ae11d2a)

If I increase the value of `icp_fitness_score` to **0.35**, more loops would be accepted and I would be able to see more point clouds (please see figures below). But the 3 maps were still not fused and I'm not able to obtain a loop closed global map.

![Accept the loop](https://github.com/MaverickPeter/MR_SLAM/assets/43923666/256ee295-8e2a-4437-a02d-1d2738d867e8)

![point cloud without routes](https://github.com/MaverickPeter/MR_SLAM/assets/43923666/8591015a-5c51-4a63-9965-bb47558d2f81)

So is there any possible reason for this? 
I'm guessing is the default parameters setting in the Docker fit for the full usage demo? What are the other important parameters that I need to fine-tune to obtain the good loop closure results for the full usage demo? 

Cheers.

Best Regards,
William

**Comment by MaverickPeter** [comment]
Hi @WilliamWoo45, it's weird that the loops are added (black lines in the third image), but the optimization is not working. There might be some outliers in the graph that cause this problem. I'll try to reproduce this issue and fix it next week.

**Comment by diamonazreal** [comment]
> Hi @MaverickPeter,
> 
> Thanks for your update and release of the full usage demo!
> 
> I've tried to run the full usage bags in Docker. However, I found that if the parameter `icp_fitness_score` is set at **0.1 by default**, most of the loop candidates would be rejected and the point cloud maps are only partially shown (please see figures below).
> 
> ![Reject the loop](https://user-images.githubusercontent.com/43923666/248249074-14ff01fd-23de-4f67-87fe-56a023ed1525.jpg)
> 
> ![point clouds](https://user-images.githubusercontent.com/43923666/248249088-5186804a-e544-4982-b69f-ad23091b0efd.jpg)
> 
> ![point cloud with routes](https://user-images.githubusercontent.com/43923666/248250869-ae3839cf-2713-45d3-bd44-838f5ae11d2a.jpg)
> 
> If I increase the value of `icp_fitness_score` to **0.35**, more loops would be accepted and I would be able to see more point clouds (please see figures below). But the 3 maps were still not fused and I'm not able to obtain a loop closed global map.
> 
> ![Accept the loop](https://user-images.githubusercontent.com/43923666/248249906-256ee295-8e2a-4437-a02d-1d2738d867e8.jpg)
> 
> ![point cloud without routes](https://user-images.githubusercontent.com/43923666/248249929-8591015a-5c51-4a63-9965-bb47558d2f81.jpg)
> 
> So is there any possible reason for this? I'm guessing is the default parameters setting in the Docker fit for the full usage demo? What are the other important parameters that I need to fine-tune to obtain the good loop closure results for the full usage demo?
> 
> Cheers.
> 
> Best Regards, William

What version of video card driver are you using

**Comment by DioBakery** [comment]
Have you solved it? I have also encountered this problem
