### ISSUE TITLE
Replace front-end odometry？

### ISSUE THREAD

**Issue by Joosoo1** [MaverickPeter/MR_SLAM#9]
Hello author, thank you very much for open sourcing this project. I am very interested in this project, I also want to do a set of multi-computer SLAM system, may I ask you this module to support the replacement of other front-end odometry, that MR_SLAM seems to support only FAST_lio2 and A_LOAM, I want to replace the other odometry integrated into this system, may I ask that the system has a special requirement for odometry?

**Comment by MaverickPeter** [comment]
@Joosoo1 Hi Joosoo, thanks for following our work, the odometry in our pipeline only serves as a submap generator. You can write your own odometry refer to the [submapGenerator.cpp.](https://github.com/MaverickPeter/MR_SLAM/blob/main/Localization/src/A-LOAM/src/ALOAMSubmapPublisher.cpp) Also, you need to modify the frameid in the odometry to distinguish different robots' names.

**Comment by Joosoo1** [comment]
Thanks for your reply, I have successfully integrated other Lio into MR_SLAM and it looks great, thanks for open sourcing this highly encouraging work. Below build the graph results:
![Multi-computer mapping results](https://github.com/MaverickPeter/MR_SLAM/assets/65029285/64ff8733-de18-4665-82d2-db2341374fcc)

**Comment by Joosoo1** [comment]
Also, I have a question for you, does the submap have to be a pointcloud？ And can it be replaced with an OccupancyGrid map, because in practice raster maps are easier to transfer. For some work, I need to utilize the OccupancyGrid map, which is transferred between multiple robots, for global map construction. I've tried a lot of methods for mutil_grid_map  so far, but the results are not obvious, so I'm begging you to give me some suggestions!

**Comment by MaverickPeter** [comment]
Hi @Joosoo1, In the current version, the submap has to be a pointcloud. It's a good idea to transport Occupancy Grid maps between multiple robots and I'll add this feature in the next version.

**Comment by Joosoo1** [comment]
OK, I'll continue my research in this area as well and look forward to your next version!

**Comment by diamonazreal** [comment]
@Joosoo1 What version of GPU driver are you using？

**Comment by Joosoo1** [comment]
> @Joosoo1 What version of GPU driver are you using？
Driver Version: 535.113.01

**Comment by diamonazreal** [comment]
@Joosoo1 What kind of GPU are you using？I used 3060GPU, but it failed.

**Comment by Joosoo1** [comment]
> @Joosoo1 What kind of GPU are you using？I used 3060GPU, but it failed.

4060GPU

**Comment by Joosoo1** [comment]
3060GPU should be enough to run this program, maybe it's something else that's causing it to fail

**Comment by diamonazreal** [comment]
@Joosoo1 Thank you for your reply. Did you use Docker for the reproduction or did you configure and reproduce the environment directly on Ubuntu20.04 system? I am looking forward to discussing the details of the reproduction with you. Looking forward to your reply
